spring.application.name=HospitalCRUD
spring.profiles.active=spring

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Hospital}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.main.allow-bean-definition-overriding=true

application.security.jwt.secret-key=${JWT_KEY:random}
#a day
application.security.jwt.expiration=86400000
#7 days
application.security.jwt.refresh-token.expiration=604800000
