name: Build Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: |
          cd SpringBoot
          mvn clean package -DskipTests
          docker build -t ghcr.io/s4nxez/medcenter-back:latest .
          docker push ghcr.io/s4nxez/medcenter-back:latest

      - name: Build frontend
        run: |
          cd ClienteJS
          docker build -t ghcr.io/s4nxez/medcenter-front:latest .
          docker push ghcr.io/s4nxez/medcenter-front:latest
